### ISSUE TITLE
GoogleDoc Mapping Reference: missing RT and misplaced RB

### ISSUE THREAD

**Issue by Raton-Laveur** [darthcloud/BlueRetroWiki#2]
Regarding https://docs.google.com/spreadsheets/d/e/2PACX-1vT9rPK2__komCjELFpf0UYz0cMWwvhAXgAU7C9nnwtgEaivjsh0q0xeCEiZAMA-paMrneePV7IqdX48/pubhtml : 

- "Xbox One S/XS" column has missing info on "PAD_RS" line: should be "RB"
- "Xbox One S/XS" column has misplaced info on "PAD_RM" line: should be "RT"

Can't edit or put pull request on the Googledoc, hence this issue.

**Comment by darthcloud** [comment]
Thanks! fixed
