### ISSUE TITLE
GoogleDoc Mapping Reference: missing MT for 8bitdo M30

### ISSUE THREAD

**Issue by Raton-Laveur** [darthcloud/BlueRetroWiki#6]
⬜Column "8bitdo M30", line "GP: MT" : cell is empty. 
▶ Cell should be "Home". 

❕ Googledoc title on first line has 1.8.4 version, should now be 1.9. 

💡Suggestion: [freeze first row and columns](https://support.google.com/docs/answer/9060449?hl=en&sjid=1571569710406650815-EU), so information can be looked up even on small screens/windows.

**Comment by darthcloud** [comment]
The original document row and columns are freeze, but the html version loose that unfortunately.

I'll have to check for the M30 I'm not sure if the Home button work in Xinput mode.

**Comment by darthcloud** [comment]
Ok yes it does work. Added to both gdocs and web (beta)
