### ISSUE TITLE
 GoogleDoc Mapping Reference: missing MQ for 8bitdo M30 / Spelling / update reference

### ISSUE THREAD

**Issue by Raton-Laveur** [darthcloud/BlueRetroWiki#8]
⬜Column "8bitdo M30", line "GP: MQ" : cell is empty.
▶ Cell should be "Star". ([named as such in the M30 manual](https://download.8bitdo.com/Manual/Controller/M30/M30_Manual.pdf?20220513))

❕ "MQ" Line on "Google Stadia" column is misspelled: "Assitant"
▶ Cell should be "Assistant". 

❕ GamePad Alt mode is shown differently in the reference on top of GoogleDoc and inside the GoogleDoc: reference shows up as red-colored cells, whereas they are shown as "*" inside the document (e.g. columns "3DO", "MD / Genesis", "Saturn", "Dreamcast"). 
▶ "*" should be removed from cells and cells should be changed to red background.

**Comment by darthcloud** [comment]
The M30 in Xinput mode (the only mode i support) the Star button doesnt do anything.

Fixed Stadia typo.

I got the alternating color generated automatically not which prevent be from having some cell in different color.

I updated legend to add the "*" mark.
